# Specifiy OS
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
#    - os: osx
#      osx_image: xcode7.2

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Install dependencies
addons:
  apt:
    packages:
      - libssl-dev
      - libboost1.54-dev
      - libboost1.54-all-dev
      - libdb5.1-dev
      - libdb5.1++-dev
      - libminiupnpc-dev

before_install:
  # workaround clang not system wide, fail on sudo make install
  - $CC --version
  - which $CC
 
  # workaround clang not system wide, fail on sudo make install
  - export CC=`which $CC`

# Build steps
script:
  - cd src/secp256k1/
  - chmod +x ./autogen.sh
  - ./autogen.sh
  - ./configure -prefix=/usr
  - sudo make install
  - cd ../
  - make -f makefile.unix
